name: Release Suite

on:
  push:
    tags:
      - test.**
      - release.**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dataplane publish workflow
        env:
          GH_TOKEN: ${{ secrets.C3PO_ACCESS_TOKEN }}
        run: |
          gh workflow run publish.yaml \
            --repo Observo-Inc/dataplane-build \
            --ref main \
            -f git_ref=${{ github.ref }} \
            -f channel=custom
